default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: dev
  password: jrchg24300142
  database: portfolio_development

test:
  <<: *default
  username: dev
  password: jrchg24300142
  database: portfolio_test

production:
  <<: *default
  username: dev
  password: <%= ENV['PORTFOLIO-RAILS_DATABASE_PASSWORD'] %>
  database: portfolio
